"""add price and mkt_value to holdings

Revision ID: 18d0fdf91d1f
Revises: fd6e8b0d5b54
Create Date: 2026-07-03 21:49:38.765071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18d0fdf91d1f'
down_revision: Union[str, Sequence[str], None] = 'fd6e8b0d5b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holdings', sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('holdings', sa.Column('mkt_value', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holdings', 'mkt_value')
    op.drop_column('holdings', 'price')
    # ### end Alembic commands ###
