"""add error_message to statements

Revision ID: fd6e8b0d5b54
Revises: 68fa5cbc9b3f
Create Date: 2026-06-28 20:29:05.568928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6e8b0d5b54'
down_revision: Union[str, Sequence[str], None] = '68fa5cbc9b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statements', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statements', 'error_message')
    # ### end Alembic commands ###
